# Generated by Django 3.1.5 on 2021-02-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, null=True)),
                ('contenu', models.CharField(max_length=1000, null=True)),
                ('categorie', models.CharField(choices=[('Arnaque', 'Arnaque'), ('Sextorsion', 'Sextorsion'), ('Information', 'Information'), ('Sensibilisation', 'Sensibilisation'), ('Escroquerie', 'Escroquerie')], max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
