# Generated by Django 3.1.5 on 2021-02-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0003_auto_20210208_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceuil',
            name='image',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
