# Generated by Django 3.1.5 on 2021-02-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_auto_20210210_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceuil',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
