# Generated by Django 3.1.5 on 2021-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensibilisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensibilisation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensibilisation',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
